config/routes.rb
Rails.application.routes.draw do
  get 'cleans/index'
  devise_for :users
  get 'mains/index'
  get 'tops/index'
  root to: 'tops#index'

  resources :cleans do
    resources :messages, only: [:create]
    resources :tasks, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clean.rb
class Clean < ApplicationRecord
  with_options presence: true do
    validates :image
    validates :clean_name
    validates :text
    validates :cleaning_place
  end

  with_options presence: true, numericality: { other_than: 1 } do
    validates :status_id
    validates :support_id
    validates :important_id
  end

  belongs_to :user
  has_one :done
  has_one_attached :image
  has_one :run2
  has_many :messages

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :status
  belongs_to_active_hash :support
  belongs_to_active_hash :important
end

app/models/done.rb
class Done < ApplicationRecord
  belongs_to :user
  belongs_to :clean
  has_one :run
end

app/models/important.rb
class Important < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '低' },
    { id: 3, name: '中' },
    { id: 4, name: '高' }
  ]

  include ActiveHash::Associations
  has_many :cleans
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :clean
end

app/models/run2.rb
class Run2 < ApplicationRecord
  belongs_to :done
  belongs_to :clean
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '汚れ' },
    { id: 3, name: '破損' },
    { id: 4, name: '紛失' },
    { id: 5, name: '異臭' },
    { id: 6, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :cleans
end

app/models/support.rb
class Support < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '不要' },
    { id: 3, name: '必要' }
  ]

  include ActiveHash::Associations
  has_many :cleans
end

app/models/task.rb
class Task
  include ActiveModel::Model
  attr_accessor :user_id, :run_id, :clean_id, :run_time, :run_content, :takeover, :note

  with_options presence: true do
    validates :run_time
    validates :run_content
    validates :takeover
    validates :user_id
    validates :clean_id
  end

  def save
    done = Done.create(user_id: user_id, clean_id: clean_id)
    Run2.create(run_time: run_time, run_content: run_content, takeover: takeover, note: note, done_id: done.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  has_many :cleans
  has_many :dones
  has_one :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    cleans_index_path
  end

  def after_sign_out_path_for(_resource)
    tops_index_path
  end

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cleans_controller.rb
class CleansController < ApplicationController
  before_action :set_clean, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :redirect_root, only: [:edit, :update]

  def index
    @cleans = Clean.order('created_at DESC')
  end

  def new
    @clean = Clean.new
  end

  def create
    @clean = Clean.new(clean_params)
    if @clean.save
      redirect_to cleans_index_path
    else
      render :new
    end
  end

  def show
    @message = Message.new
    @messages = @clean.messages.includes(:user)
  end

  def edit
  end

  def update
    if @clean.update(clean_params)
      redirect_to clean_path
    else
      render :edit
    end
  end

  def destroy
    clean = Clean.find(params[:id])
    if clean.destroy
      redirect_to cleans_index_path
    else
      redirect_to edit_clean_path
    end
    redirect_to root_path unless current_user == clean.user
  end

  private

  def clean_params
    params.require(:clean).permit(:image, :clean_name, :text, :cleaning_place, :status_id, :support_id,
                                  :important_id).merge(user_id: current_user.id)
  end

  def set_clean
    @clean = Clean.find(params[:id])
  end

  def redirect_root
    redirect_to root_path unless current_user == @clean.user
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = Message.create(message_params)
    if  @message.save
      ActionCable.server.broadcast "message_channel", message: @message
    end
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id, clean_id: params[:clean_id])
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:index, :create]
  before_action :authenticate_user!, only: [:index, :create]

  def index
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to cleans_index_path
    else
      render root_path
    end
  end

  private

  def task_params
    params.require(:task).permit(:image2, :run_time, :run_content, :takeover, :note).merge(user_id: current_user.id,
                                                                                           clean_id: params[:clean_id])
  end

  def set_task
    @clean = Clean.find(params[:clean_id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cleans_helper.rb
module CleansHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/cleans/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>
<%= render "shared/second-header" %>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">清掃内容の情報を入力</h2>
    <%= form_with(model: @clean, local: true) do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        タスク場所画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :hoge, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        清掃タスク名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :clean_name, class:"items-text", id:"clean-name", placeholder:"タスク名を入力", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          タスクの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"clean-info", placeholder:"説明（タスクについての説明。どう言った状態なのか、細かな情報、注意点など）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

        <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">タスクの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          清掃場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :cleaning_place, class:"items-text", id:"cleaning-pleace", placeholder:"場所を入力", maxlength:"40" %>
        <div class="weight-bold-text">
          清掃箇所の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"clean-status"}) %>
                <div class="weight-bold-text">
          業者対応の有無
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:support_id, Support.all, :id, :name, {}, {class:"select-box", id:"clean-support"}) %>
        <div class="weight-bold-text">
          重要度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:important_id, Important.all, :id, :name, {}, {class:"select-box", id:"clean-important"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%= link_to '戻る', 'javascript:history.back()', class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>


</div>
<%= render "shared/footer"%>

app/views/cleans/index.html.erb
<%= render "shared/second-header" %>

  <div class='item-contents'>
    <h2 class='title'>タスク投稿一覧</h2>
    <ul class='item-lists'>
      <% @cleans.each do |clean|%>
      <li class='list'>
        <div class='item-img-content'>
          <%= link_to image_tag(clean.image, class: "item-img"), clean_path(clean) %>

          <% if clean.done.present? %>
          <div class='complete'>
          <%= image_tag("complete.png") %>
          </div>
          <% end %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= clean.clean_name %>
          </h3>
          <div class='item-price'>
            <span><%= clean.status.name %></span>
            <div class='pleace'>
              <%= clean.cleaning_place %>
            </div>
          </div>
        </div>
      </li>
      <% end %>
      <%# //投稿がない場合、サンプル投稿を表示%>
       <li class='list'>
        <% if @cleans.length == 0 %>
        <%= image_tag "sample_clean.jpg", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            サンプル投稿
          </h3>
          <div class='item-price'>
            <span>タスク完了で完了表示されます</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
      <%# //投稿がない場合、サンプル投稿を表示%>
    </ul>
  </div>
  <%= render "shared/footer"%>

app/views/cleans/new.html.erb
<%= render "shared/second-header" %>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <h2 class="items-sell-title">清掃内容の情報を入力</h2>
    <%= form_with(model: @clean,local: true) do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <%= render 'shared/error_messages', model: f.object %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        タスク場所画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"clean-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        清掃タスク名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :clean_name, class:"items-text", id:"clean-name", placeholder:"タスク名を入力", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          タスクの説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"clean-info", placeholder:"説明（タスクについての説明。どう言った状態なのか、細かな情報、注意点など）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">タスクの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          清掃場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :cleaning_place, class:"items-text", id:"cleaning-pleace", placeholder:"場所を入力", maxlength:"40" %>
        <div class="weight-bold-text">
          清掃箇所の状態
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"select-box", id:"clean-status"}) %>
                <div class="weight-bold-text">
          業者対応の有無
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:support_id, Support.all, :id, :name, {}, {class:"select-box", id:"clean-support"}) %>
        <div class="weight-bold-text">
          重要度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:important_id, Important.all, :id, :name, {}, {class:"select-box", id:"clean-important"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
 <%= render "shared/footer"%>

app/views/cleans/show.html.erb
<%= render "shared/second-header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @clean.clean_name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag(@clean.image,class:"item-box-img") %>

      <% if @clean.done.present? %> 
          <div class='complete2'>
          <%= image_tag("complete.png") %>
          </div>
      <% end %>
  
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @clean.text %>
      </span>
      <span class="item-postage">
        <%= @clean.status.name %>
      </span>
    </div>

    <%# ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>
    <% unless @clean.done.present? %>
    <%= link_to "タスク投稿の編集", edit_clean_path, method: :get, class: "item-red-btn" %>
    <%= link_to "タスク完了の報告", clean_tasks_path(@clean.id), class:"item-red-btn"%>
    <%= link_to "投稿を削除", clean_path(@clean.id), method: :delete, data: {confirm: "削除しますか？"}, class:"item-destroy" %>
    <% end %>

    <%# //ログインしているユーザーと出品しているユーザーが、同一人物の場合と同一人物ではない場合で、処理を分けましょう %>

    <div class="item-explain-box">
      <span><%= "タスク説明" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">タスク名</th>
          <td class="detail-value"><%= @clean.clean_name %></td>
        </tr>
        <tr>
          <th class="detail-item">清掃場所</th>
          <td class="detail-value"><%= @clean.cleaning_place %></td>
        </tr>
        <tr>
          <th class="detail-item">清掃箇所の状態</th>
          <td class="detail-value"><%= @clean.status.name %></td>
        </tr>
        <tr>
          <th class="detail-item">業者対応の有無</th>
          <td class="detail-value"><%= @clean.support.name %></td>
        </tr>
        <tr>
          <th class="detail-item">重要度</th>
          <td class="detail-value"><%= @clean.important.name %></td>
        </tr>
      </tbody>
    </table>

  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <%= form_with(model:[@clean, @message], local: true) do |f|%>
    <%= f.text_area :text, placeholder: "ここにコメントを入力", rows: "2", class: "comment-text" %>
      <%= f.submit "コメントする", class: "comment-btn" %>
      <% end %>
  </div>
  <h2>＜コメント一覧＞</h2>
  <div id='messages'>
    <% @messages.reverse_each do |message| %>
      <p><%= message.text %></p>
    <% end %>
  </div>
  <%# 詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
  <%= link_to 'TOPに戻る', cleans_index_path, class: "top-move" %>
  <%# //詳細ページで表示されている商品のカテゴリー名を表示しましょう %>
</div>

 <%= render "shared/footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CleanlinessMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='ad-footer-contents'>
<%= link_to image_tag("logow.png", class:"logo"), "#" %>
<p>Copyright©2021TIME MACHINE Inc. All rights reserved. 写真の無断転載、文面の転用、  デザインの無断転用は固く禁じます。</p>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='top-bar-contents'>
  <div class='nav'>
    <%= link_to image_tag("logo.png", class:"clean-icon"), "/" %>
    <ul class='lists-right'>
    <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
    </ul>
    </div>
  </div>
</header>

app/views/shared/_second-header.html.erb
<header class='top-page-header'>
  <div class='top-bar-contents'>
   <div class='nav'>
     <%= link_to image_tag("logo.png", class:"clean-icon"), cleans_index_path %>
      <ul class='lists-right'>
        <li><%= link_to '新規タスク投稿', new_clean_path, class: "newpost" %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "logout" %></li>
      </ul>
   </div>
  </div>
</header>

app/views/tasks/index.html.erb
<%= render "shared/second-header" %>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      タスク内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @clean.image, class: 'buy-item-img' %>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @clean.clean_name %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'><%= @clean.cleaning_place %></p>
          <p class='item-price-sub-text'><%= @clean.status.name %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%= form_with(model: @task, url: clean_tasks_path, id: 'charge-form', local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <%# 完了報告の入力 %>
    <div class='done-form'>
      <h1 class='info-input-haedline'>
        完了報告
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">完了日時</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.date_field :run_time, class:"input-default", id:"run-time" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">改善内容</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :run_content, class:"item-text", id:"run-content" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">引継ぎ内容</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :takeover, class:"item-text", id:"takeover" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">備考欄</label>
        </div>
        <%= f.text_area :note, class:"item-text", id:"note" %>
      </div>
    </div>
    <%# /完了報告の入力 %>
    <div class='complete-btn'>
      <%= f.submit "完了" ,class:"complete-red-btn" %>
      <%= link_to '戻る', 'javascript:history.back()', class:"back-btn" %>
    </div>
    <% end %>
  </div>
</div>

 <%= render "shared/footer"%>

app/views/tops/index.html.erb
<%= render "shared/header" %>

<%# Top %>
  <div class='title-contents'>
    <h2 class='service-title'>
      クレンリネンス共有タスクアプリ
    </h2>
    <p class='service-explain'>
    【清潔で快適な状態】をチームで共有するための、写真投稿によるタスク化アプリです。
    </p>
    <ul style="list-style: none;">
    <li><%= link_to 'Cleanliness_meを始める', new_user_registration_path, class: "btn btn-primary" %></li>
    </ul>
  </div>

<%# 詳細 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      Cleanliness_meの特徴
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag("im.png", class:"list-pict") %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>写真</span>
          をつけて簡単投稿
        </h3>
        <p class='reason-list-description'>
          写真を付けて、状況が分かりやすく、使い方も簡単。
        </p>
      </li>
      <li class='list'>
        <%= image_tag("tsk.png", class:"list-pict") %>
        <h3 class='reason-list-text'>
        見やすい
          <span class='reason-list-blue-text'>一覧</span>
          表示
        </h3>
        <p class='reason-list-description'>
          シンプルな一覧表示で情報が見やすく、使いやすい。
        </p>
      </li>
      <li class='list'>
        <%= image_tag("com.png", class:"list-pict") %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>完了表示</span>
          で簡潔
        </h3>
        <p class='reason-list-description'>
          完了表示で、未完了タスクと見分けがしやすい。
        </p>
      </li>
    </ul>
  </div>

<%# Footer %>
<%= render "shared/footer"%>